project:
  type: book

book:
  title: |
    Code and data for "<paper title>"
  author: 
    - name: Your name
      orcid: Your ORCID
  date: "year"
  chapters:
    - index.qmd
    - chapters/chapter_01.qmd
    - chapters/chapter_02.qmd
    - chapters/appendices.qmd

bibliography: bibliography.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo

editor: 
  mode: source